### ISSUE TITLE
Parallel States and aggregated results

### ISSUE THREAD

**Issue by meenahoda** [wmfs/statebox#20]
See issue: https://github.com/wmfs/tymly/issues/452 by @pmotyka

**Comment by pmotyka** [comment]
Thanks for the quick fix!  Is there a timeline as to when this will be published to npm?

**Comment by meenahoda** [comment]
No problem! That should be published to npm now as version 1.3.1.

**Comment by pmotyka** [comment]
I gave this a closer look and am observing odd behavior, consider the following test scenario: https://github.com/pmotyka/statebox/commit/bcf690fe7d1de9408fbce88e90a70bcd4e57c903.  The outcome here are results being aggregated across state executions.  Shouldn't the expectation be that results are scoped to a respective state execution?  Output of the test is as follows:

<pre>
  1 failing

  1) State machines
       Using built in DAO
         parallel - state machine with parallel states and results
           waitUntilStoppedRunning2:

      AssertionError: expected [ 'F', 'G', 'F', 'G' ] to have a length of 2 but got 4
      + expected - actual

      -4
      +2
</pre>

**Comment by meenahoda** [comment]
Hi,

I've made a commit (https://github.com/wmfs/statebox/commit/f31b19ab96b280536f523f2dca45305a272f152b) which resets the context in the parallel branch tracker each time start execution is called. The tests have been amended to repeat the same execution 3 times to ensure the results are the same throughout.

I hope this helps!
Meena

**Comment by pmotyka** [comment]
Thanks again for the prompt attention to the issue!  Really appreciate the effort.

Peter

**Comment by pmotyka** [comment]
Gave this a close look and seems to be working great now, feel free to close out the issue.  Thanks again!

**Comment by meenahoda** [comment]
Good to hear! No problem. 😄 

Meena
